/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.27.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.apps.models.V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithCandidate;
import io.kubeblocks.apps.models.V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithoutCandidate;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Defines command to do switchover. In particular, when workloadType&#x3D;Replication, the command defined in switchoverSpec will only be executed under the condition of cluster.componentSpecs[x].SwitchPolicy.type&#x3D;Noop.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-13T15:59:08.817252Z[Etc/UTC]")
public class V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec {
  public static final String SERIALIZED_NAME_WITH_CANDIDATE = "withCandidate";
  @SerializedName(SERIALIZED_NAME_WITH_CANDIDATE)
  private V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithCandidate withCandidate;

  public static final String SERIALIZED_NAME_WITHOUT_CANDIDATE = "withoutCandidate";
  @SerializedName(SERIALIZED_NAME_WITHOUT_CANDIDATE)
  private V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithoutCandidate withoutCandidate;

  public V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec() {
  }

  public V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec withCandidate(V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithCandidate withCandidate) {
    
    this.withCandidate = withCandidate;
    return this;
  }

   /**
   * Get withCandidate
   * @return withCandidate
  **/
  @jakarta.annotation.Nullable
  public V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithCandidate getWithCandidate() {
    return withCandidate;
  }


  public void setWithCandidate(V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithCandidate withCandidate) {
    this.withCandidate = withCandidate;
  }


  public V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec withoutCandidate(V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithoutCandidate withoutCandidate) {
    
    this.withoutCandidate = withoutCandidate;
    return this;
  }

   /**
   * Get withoutCandidate
   * @return withoutCandidate
  **/
  @jakarta.annotation.Nullable
  public V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithoutCandidate getWithoutCandidate() {
    return withoutCandidate;
  }


  public void setWithoutCandidate(V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithoutCandidate withoutCandidate) {
    this.withoutCandidate = withoutCandidate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec v1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec = (V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec) o;
    return Objects.equals(this.withCandidate, v1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.withCandidate) &&
        Objects.equals(this.withoutCandidate, v1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.withoutCandidate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(withCandidate, withoutCandidate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec {\n");
    sb.append("    withCandidate: ").append(toIndentedString(withCandidate)).append("\n");
    sb.append("    withoutCandidate: ").append(toIndentedString(withoutCandidate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("withCandidate");
    openapiFields.add("withoutCandidate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec is not found in the empty JSON string", V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `withCandidate`
      if (jsonObj.get("withCandidate") != null && !jsonObj.get("withCandidate").isJsonNull()) {
        V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithCandidate.validateJsonObject(jsonObj.getAsJsonObject("withCandidate"));
      }
      // validate the optional field `withoutCandidate`
      if (jsonObj.get("withoutCandidate") != null && !jsonObj.get("withoutCandidate").isJsonNull()) {
        V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpecWithoutCandidate.validateJsonObject(jsonObj.getAsJsonObject("withoutCandidate"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec>() {
           @Override
           public void write(JsonWriter out, V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec
  * @throws IOException if the JSON string is invalid with respect to V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec
  */
  public static V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec fromJson(String jsonString) throws IOException {
    return new JSON().getGson().fromJson(jsonString, V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec.class);
  }

 /**
  * Convert an instance of V1alpha1ClusterDefinitionSpecComponentDefsInnerSwitchoverSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return new JSON().getGson().toJson(this);
  }
}

