/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * cluster backup configuration.
 */
@ApiModel(description = "cluster backup configuration.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T07:24:37.743Z[Etc/UTC]")
public class V1alpha1ClusterSpecBackup {
  public static final String SERIALIZED_NAME_CRON_EXPRESSION = "cronExpression";
  @SerializedName(SERIALIZED_NAME_CRON_EXPRESSION)
  private String cronExpression;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  private String method;

  public static final String SERIALIZED_NAME_PITR_ENABLED = "pitrEnabled";
  @SerializedName(SERIALIZED_NAME_PITR_ENABLED)
  private Boolean pitrEnabled;

  public static final String SERIALIZED_NAME_REPO_NAME = "repoName";
  @SerializedName(SERIALIZED_NAME_REPO_NAME)
  private String repoName;

  public static final String SERIALIZED_NAME_RETENTION_PERIOD = "retentionPeriod";
  @SerializedName(SERIALIZED_NAME_RETENTION_PERIOD)
  private String retentionPeriod;

  public static final String SERIALIZED_NAME_STARTING_DEADLINE_MINUTES = "startingDeadlineMinutes";
  @SerializedName(SERIALIZED_NAME_STARTING_DEADLINE_MINUTES)
  private Long startingDeadlineMinutes;


  public V1alpha1ClusterSpecBackup cronExpression(String cronExpression) {
    
    this.cronExpression = cronExpression;
    return this;
  }

   /**
   * the cron expression for schedule, the timezone is in UTC. see https://en.wikipedia.org/wiki/Cron.
   * @return cronExpression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the cron expression for schedule, the timezone is in UTC. see https://en.wikipedia.org/wiki/Cron.")

  public String getCronExpression() {
    return cronExpression;
  }


  public void setCronExpression(String cronExpression) {
    this.cronExpression = cronExpression;
  }


  public V1alpha1ClusterSpecBackup enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * enabled defines whether to enable automated backup.
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "enabled defines whether to enable automated backup.")

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public V1alpha1ClusterSpecBackup method(String method) {
    
    this.method = method;
    return this;
  }

   /**
   * backup method name to use, that is defined in backupPolicy.
   * @return method
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "backup method name to use, that is defined in backupPolicy.")

  public String getMethod() {
    return method;
  }


  public void setMethod(String method) {
    this.method = method;
  }


  public V1alpha1ClusterSpecBackup pitrEnabled(Boolean pitrEnabled) {
    
    this.pitrEnabled = pitrEnabled;
    return this;
  }

   /**
   * pitrEnabled defines whether to enable point-in-time recovery.
   * @return pitrEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "pitrEnabled defines whether to enable point-in-time recovery.")

  public Boolean getPitrEnabled() {
    return pitrEnabled;
  }


  public void setPitrEnabled(Boolean pitrEnabled) {
    this.pitrEnabled = pitrEnabled;
  }


  public V1alpha1ClusterSpecBackup repoName(String repoName) {
    
    this.repoName = repoName;
    return this;
  }

   /**
   * repoName is the name of the backupRepo, if not set, will use the default backupRepo.
   * @return repoName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "repoName is the name of the backupRepo, if not set, will use the default backupRepo.")

  public String getRepoName() {
    return repoName;
  }


  public void setRepoName(String repoName) {
    this.repoName = repoName;
  }


  public V1alpha1ClusterSpecBackup retentionPeriod(String retentionPeriod) {
    
    this.retentionPeriod = retentionPeriod;
    return this;
  }

   /**
   * retentionPeriod determines a duration up to which the backup should be kept. controller will remove all backups that are older than the RetentionPeriod. For example, RetentionPeriod of &#x60;30d&#x60; will keep only the backups of last 30 days. Sample duration format: - years:  2y - months:  6mo - days:   30d - hours:  12h - minutes:  30m You can also combine the above durations. For example: 30d12h30m
   * @return retentionPeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "retentionPeriod determines a duration up to which the backup should be kept. controller will remove all backups that are older than the RetentionPeriod. For example, RetentionPeriod of `30d` will keep only the backups of last 30 days. Sample duration format: - years:  2y - months:  6mo - days:   30d - hours:  12h - minutes:  30m You can also combine the above durations. For example: 30d12h30m")

  public String getRetentionPeriod() {
    return retentionPeriod;
  }


  public void setRetentionPeriod(String retentionPeriod) {
    this.retentionPeriod = retentionPeriod;
  }


  public V1alpha1ClusterSpecBackup startingDeadlineMinutes(Long startingDeadlineMinutes) {
    
    this.startingDeadlineMinutes = startingDeadlineMinutes;
    return this;
  }

   /**
   * startingDeadlineMinutes defines the deadline in minutes for starting the backup job if it misses scheduled time for any reason.
   * minimum: 0
   * maximum: 1440
   * @return startingDeadlineMinutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "startingDeadlineMinutes defines the deadline in minutes for starting the backup job if it misses scheduled time for any reason.")

  public Long getStartingDeadlineMinutes() {
    return startingDeadlineMinutes;
  }


  public void setStartingDeadlineMinutes(Long startingDeadlineMinutes) {
    this.startingDeadlineMinutes = startingDeadlineMinutes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ClusterSpecBackup v1alpha1ClusterSpecBackup = (V1alpha1ClusterSpecBackup) o;
    return Objects.equals(this.cronExpression, v1alpha1ClusterSpecBackup.cronExpression) &&
        Objects.equals(this.enabled, v1alpha1ClusterSpecBackup.enabled) &&
        Objects.equals(this.method, v1alpha1ClusterSpecBackup.method) &&
        Objects.equals(this.pitrEnabled, v1alpha1ClusterSpecBackup.pitrEnabled) &&
        Objects.equals(this.repoName, v1alpha1ClusterSpecBackup.repoName) &&
        Objects.equals(this.retentionPeriod, v1alpha1ClusterSpecBackup.retentionPeriod) &&
        Objects.equals(this.startingDeadlineMinutes, v1alpha1ClusterSpecBackup.startingDeadlineMinutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cronExpression, enabled, method, pitrEnabled, repoName, retentionPeriod, startingDeadlineMinutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ClusterSpecBackup {\n");
    sb.append("    cronExpression: ").append(toIndentedString(cronExpression)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    pitrEnabled: ").append(toIndentedString(pitrEnabled)).append("\n");
    sb.append("    repoName: ").append(toIndentedString(repoName)).append("\n");
    sb.append("    retentionPeriod: ").append(toIndentedString(retentionPeriod)).append("\n");
    sb.append("    startingDeadlineMinutes: ").append(toIndentedString(startingDeadlineMinutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

