/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * connectionCredential specifies the connection credential to connect to the target database cluster.
 */
@ApiModel(description = "connectionCredential specifies the connection credential to connect to the target database cluster.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T07:53:54.854Z[Etc/UTC]")
public class V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential {
  public static final String SERIALIZED_NAME_HOST_KEY = "hostKey";
  @SerializedName(SERIALIZED_NAME_HOST_KEY)
  private String hostKey;

  public static final String SERIALIZED_NAME_PASSWORD_KEY = "passwordKey";
  @SerializedName(SERIALIZED_NAME_PASSWORD_KEY)
  private String passwordKey;

  public static final String SERIALIZED_NAME_PORT_KEY = "portKey";
  @SerializedName(SERIALIZED_NAME_PORT_KEY)
  private String portKey;

  public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
  @SerializedName(SERIALIZED_NAME_SECRET_NAME)
  private String secretName;

  public static final String SERIALIZED_NAME_USERNAME_KEY = "usernameKey";
  @SerializedName(SERIALIZED_NAME_USERNAME_KEY)
  private String usernameKey;


  public V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential hostKey(String hostKey) {
    
    this.hostKey = hostKey;
    return this;
  }

   /**
   * hostKey specifies the map key of the host in the connection credential secret.
   * @return hostKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "hostKey specifies the map key of the host in the connection credential secret.")

  public String getHostKey() {
    return hostKey;
  }


  public void setHostKey(String hostKey) {
    this.hostKey = hostKey;
  }


  public V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential passwordKey(String passwordKey) {
    
    this.passwordKey = passwordKey;
    return this;
  }

   /**
   * passwordKey specifies the map key of the password in the connection credential secret. This password will be saved in the backup annotation for full backup. You can use the environment variable DP_ENCRYPTION_KEY to specify encryption key.
   * @return passwordKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "passwordKey specifies the map key of the password in the connection credential secret. This password will be saved in the backup annotation for full backup. You can use the environment variable DP_ENCRYPTION_KEY to specify encryption key.")

  public String getPasswordKey() {
    return passwordKey;
  }


  public void setPasswordKey(String passwordKey) {
    this.passwordKey = passwordKey;
  }


  public V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential portKey(String portKey) {
    
    this.portKey = portKey;
    return this;
  }

   /**
   * portKey specifies the map key of the port in the connection credential secret.
   * @return portKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "portKey specifies the map key of the port in the connection credential secret.")

  public String getPortKey() {
    return portKey;
  }


  public void setPortKey(String portKey) {
    this.portKey = portKey;
  }


  public V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential secretName(String secretName) {
    
    this.secretName = secretName;
    return this;
  }

   /**
   * secretName refers to the Secret object that contains the connection credential.
   * @return secretName
  **/
  @ApiModelProperty(required = true, value = "secretName refers to the Secret object that contains the connection credential.")

  public String getSecretName() {
    return secretName;
  }


  public void setSecretName(String secretName) {
    this.secretName = secretName;
  }


  public V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential usernameKey(String usernameKey) {
    
    this.usernameKey = usernameKey;
    return this;
  }

   /**
   * usernameKey specifies the map key of the user in the connection credential secret.
   * @return usernameKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "usernameKey specifies the map key of the user in the connection credential secret.")

  public String getUsernameKey() {
    return usernameKey;
  }


  public void setUsernameKey(String usernameKey) {
    this.usernameKey = usernameKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential v1alpha1BackupPolicyTemplateSpecTargetConnectionCredential = (V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential) o;
    return Objects.equals(this.hostKey, v1alpha1BackupPolicyTemplateSpecTargetConnectionCredential.hostKey) &&
        Objects.equals(this.passwordKey, v1alpha1BackupPolicyTemplateSpecTargetConnectionCredential.passwordKey) &&
        Objects.equals(this.portKey, v1alpha1BackupPolicyTemplateSpecTargetConnectionCredential.portKey) &&
        Objects.equals(this.secretName, v1alpha1BackupPolicyTemplateSpecTargetConnectionCredential.secretName) &&
        Objects.equals(this.usernameKey, v1alpha1BackupPolicyTemplateSpecTargetConnectionCredential.usernameKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostKey, passwordKey, portKey, secretName, usernameKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1BackupPolicyTemplateSpecTargetConnectionCredential {\n");
    sb.append("    hostKey: ").append(toIndentedString(hostKey)).append("\n");
    sb.append("    passwordKey: ").append(toIndentedString(passwordKey)).append("\n");
    sb.append("    portKey: ").append(toIndentedString(portKey)).append("\n");
    sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
    sb.append("    usernameKey: ").append(toIndentedString(usernameKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

