/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1ComponentClassDefinitionSpecClasses
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T09:04:54.369Z[Etc/UTC]")
public class V1alpha1ComponentClassDefinitionSpecClasses {
  public static final String SERIALIZED_NAME_ARGS = "args";
  @SerializedName(SERIALIZED_NAME_ARGS)
  private List<String> args = null;

  public static final String SERIALIZED_NAME_CPU = "cpu";
  @SerializedName(SERIALIZED_NAME_CPU)
  private Object cpu;

  public static final String SERIALIZED_NAME_MEMORY = "memory";
  @SerializedName(SERIALIZED_NAME_MEMORY)
  private Object memory;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1alpha1ComponentClassDefinitionSpecClasses args(List<String> args) {
    
    this.args = args;
    return this;
  }

  public V1alpha1ComponentClassDefinitionSpecClasses addArgsItem(String argsItem) {
    if (this.args == null) {
      this.args = new ArrayList<>();
    }
    this.args.add(argsItem);
    return this;
  }

   /**
   * args are variable&#39;s value
   * @return args
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "args are variable's value")

  public List<String> getArgs() {
    return args;
  }


  public void setArgs(List<String> args) {
    this.args = args;
  }


  public V1alpha1ComponentClassDefinitionSpecClasses cpu(Object cpu) {
    
    this.cpu = cpu;
    return this;
  }

   /**
   * the CPU of the class
   * @return cpu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the CPU of the class")

  public Object getCpu() {
    return cpu;
  }


  public void setCpu(Object cpu) {
    this.cpu = cpu;
  }


  public V1alpha1ComponentClassDefinitionSpecClasses memory(Object memory) {
    
    this.memory = memory;
    return this;
  }

   /**
   * the memory of the class
   * @return memory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the memory of the class")

  public Object getMemory() {
    return memory;
  }


  public void setMemory(Object memory) {
    this.memory = memory;
  }


  public V1alpha1ComponentClassDefinitionSpecClasses name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name is the class name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "name is the class name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ComponentClassDefinitionSpecClasses v1alpha1ComponentClassDefinitionSpecClasses = (V1alpha1ComponentClassDefinitionSpecClasses) o;
    return Objects.equals(this.args, v1alpha1ComponentClassDefinitionSpecClasses.args) &&
        Objects.equals(this.cpu, v1alpha1ComponentClassDefinitionSpecClasses.cpu) &&
        Objects.equals(this.memory, v1alpha1ComponentClassDefinitionSpecClasses.memory) &&
        Objects.equals(this.name, v1alpha1ComponentClassDefinitionSpecClasses.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, cpu, memory, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ComponentClassDefinitionSpecClasses {\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

