/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.27.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.apps.models.V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInnerComponentRefEnvInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ComponentDefRef is used to select the component and its fields to be referenced.   Deprecated since v0.8.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-13T15:59:08.817252Z[Etc/UTC]")
public class V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner {
  public static final String SERIALIZED_NAME_COMPONENT_DEF_NAME = "componentDefName";
  @SerializedName(SERIALIZED_NAME_COMPONENT_DEF_NAME)
  private String componentDefName;

  public static final String SERIALIZED_NAME_COMPONENT_REF_ENV = "componentRefEnv";
  @SerializedName(SERIALIZED_NAME_COMPONENT_REF_ENV)
  private List<V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInnerComponentRefEnvInner> componentRefEnv;

  public static final String SERIALIZED_NAME_FAILURE_POLICY = "failurePolicy";
  @SerializedName(SERIALIZED_NAME_FAILURE_POLICY)
  private String failurePolicy;

  public V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner() {
  }

  public V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner componentDefName(String componentDefName) {
    
    this.componentDefName = componentDefName;
    return this;
  }

   /**
   * The name of the componentDef to be selected.
   * @return componentDefName
  **/
  @jakarta.annotation.Nonnull
  public String getComponentDefName() {
    return componentDefName;
  }


  public void setComponentDefName(String componentDefName) {
    this.componentDefName = componentDefName;
  }


  public V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner componentRefEnv(List<V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInnerComponentRefEnvInner> componentRefEnv) {
    
    this.componentRefEnv = componentRefEnv;
    return this;
  }

  public V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner addComponentRefEnvItem(V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInnerComponentRefEnvInner componentRefEnvItem) {
    if (this.componentRefEnv == null) {
      this.componentRefEnv = new ArrayList<>();
    }
    this.componentRefEnv.add(componentRefEnvItem);
    return this;
  }

   /**
   * The values that are to be injected as environment variables into each component.
   * @return componentRefEnv
  **/
  @jakarta.annotation.Nullable
  public List<V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInnerComponentRefEnvInner> getComponentRefEnv() {
    return componentRefEnv;
  }


  public void setComponentRefEnv(List<V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInnerComponentRefEnvInner> componentRefEnv) {
    this.componentRefEnv = componentRefEnv;
  }


  public V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner failurePolicy(String failurePolicy) {
    
    this.failurePolicy = failurePolicy;
    return this;
  }

   /**
   * Defines the policy to be followed in case of a failure in finding the component.
   * @return failurePolicy
  **/
  @jakarta.annotation.Nullable
  public String getFailurePolicy() {
    return failurePolicy;
  }


  public void setFailurePolicy(String failurePolicy) {
    this.failurePolicy = failurePolicy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner v1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner = (V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner) o;
    return Objects.equals(this.componentDefName, v1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.componentDefName) &&
        Objects.equals(this.componentRefEnv, v1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.componentRefEnv) &&
        Objects.equals(this.failurePolicy, v1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.failurePolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(componentDefName, componentRefEnv, failurePolicy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner {\n");
    sb.append("    componentDefName: ").append(toIndentedString(componentDefName)).append("\n");
    sb.append("    componentRefEnv: ").append(toIndentedString(componentRefEnv)).append("\n");
    sb.append("    failurePolicy: ").append(toIndentedString(failurePolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("componentDefName");
    openapiFields.add("componentRefEnv");
    openapiFields.add("failurePolicy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("componentDefName");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner is not found in the empty JSON string", V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("componentDefName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `componentDefName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("componentDefName").toString()));
      }
      if (jsonObj.get("componentRefEnv") != null && !jsonObj.get("componentRefEnv").isJsonNull()) {
        JsonArray jsonArraycomponentRefEnv = jsonObj.getAsJsonArray("componentRefEnv");
        if (jsonArraycomponentRefEnv != null) {
          // ensure the json data is an array
          if (!jsonObj.get("componentRefEnv").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `componentRefEnv` to be an array in the JSON string but got `%s`", jsonObj.get("componentRefEnv").toString()));
          }

          // validate the optional field `componentRefEnv` (array)
          for (int i = 0; i < jsonArraycomponentRefEnv.size(); i++) {
            V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInnerComponentRefEnvInner.validateJsonObject(jsonArraycomponentRefEnv.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("failurePolicy") != null && !jsonObj.get("failurePolicy").isJsonNull()) && !jsonObj.get("failurePolicy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `failurePolicy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("failurePolicy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner>() {
           @Override
           public void write(JsonWriter out, V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner
  * @throws IOException if the JSON string is invalid with respect to V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner
  */
  public static V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner fromJson(String jsonString) throws IOException {
    return new JSON().getGson().fromJson(jsonString, V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner.class);
  }

 /**
  * Convert an instance of V1alpha1ClusterDefinitionSpecComponentDefsInnerComponentDefRefInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return new JSON().getGson().toJson(this);
  }
}

