/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.apps.models.V1alpha1OpsRequestStatusConditions;
import io.kubeblocks.apps.models.V1alpha1OpsRequestStatusReconfiguringStatusConfigurationStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1OpsRequestStatusReconfiguringStatusAsComponent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T05:38:56.141Z[Etc/UTC]")
public class V1alpha1OpsRequestStatusReconfiguringStatusAsComponent {
  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha1OpsRequestStatusConditions> conditions = null;

  public static final String SERIALIZED_NAME_CONFIGURATION_STATUS = "configurationStatus";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION_STATUS)
  private List<V1alpha1OpsRequestStatusReconfiguringStatusConfigurationStatus> configurationStatus = new ArrayList<>();


  public V1alpha1OpsRequestStatusReconfiguringStatusAsComponent conditions(List<V1alpha1OpsRequestStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha1OpsRequestStatusReconfiguringStatusAsComponent addConditionsItem(V1alpha1OpsRequestStatusConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * conditions describes reconfiguring detail status.
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "conditions describes reconfiguring detail status.")

  public List<V1alpha1OpsRequestStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha1OpsRequestStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1alpha1OpsRequestStatusReconfiguringStatusAsComponent configurationStatus(List<V1alpha1OpsRequestStatusReconfiguringStatusConfigurationStatus> configurationStatus) {
    
    this.configurationStatus = configurationStatus;
    return this;
  }

  public V1alpha1OpsRequestStatusReconfiguringStatusAsComponent addConfigurationStatusItem(V1alpha1OpsRequestStatusReconfiguringStatusConfigurationStatus configurationStatusItem) {
    this.configurationStatus.add(configurationStatusItem);
    return this;
  }

   /**
   * configurationStatus describes the status of the component reconfiguring.
   * @return configurationStatus
  **/
  @ApiModelProperty(required = true, value = "configurationStatus describes the status of the component reconfiguring.")

  public List<V1alpha1OpsRequestStatusReconfiguringStatusConfigurationStatus> getConfigurationStatus() {
    return configurationStatus;
  }


  public void setConfigurationStatus(List<V1alpha1OpsRequestStatusReconfiguringStatusConfigurationStatus> configurationStatus) {
    this.configurationStatus = configurationStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1OpsRequestStatusReconfiguringStatusAsComponent v1alpha1OpsRequestStatusReconfiguringStatusAsComponent = (V1alpha1OpsRequestStatusReconfiguringStatusAsComponent) o;
    return Objects.equals(this.conditions, v1alpha1OpsRequestStatusReconfiguringStatusAsComponent.conditions) &&
        Objects.equals(this.configurationStatus, v1alpha1OpsRequestStatusReconfiguringStatusAsComponent.configurationStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, configurationStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1OpsRequestStatusReconfiguringStatusAsComponent {\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    configurationStatus: ").append(toIndentedString(configurationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

